### ISSUE TITLE
Error Running On Windows

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [urketadic/mirror_trader#7]
SyntaxError: Unexpected token '/' in C:\Users\********\Downloads\mirror_trader\admin\views\app.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (C:\Users\********\Downloads\mirror_trader\admin\node_modules\ejs\lib\ejs.js:673:12)
    at Object.compile (C:\Users\********\Downloads\mirror_trader\admin\node_modules\ejs\lib\ejs.js:398:16)
    at handleCache (C:\Users\********\Downloads\mirror_trader\admin\node_modules\ejs\lib\ejs.js:235:18)
    at tryHandleCache (C:\Users\********\Downloads\mirror_trader\admin\node_modules\ejs\lib\ejs.js:274:16)
    at View.exports.renderFile [as engine] (C:\Users\********\Downloads\mirror_trader\admin\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\********\Downloads\mirror_trader\admin\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\********\Downloads\mirror_trader\admin\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\********\Downloads\mirror_trader\admin\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\********\Downloads\mirror_trader\admin\node_modules\express\lib\response.js:1012:7)

**Comment by MxyzptlkFishStix** [comment]
I put (" ") around the file names in the include statements. No error message anymore. However, when I click on the exchanges, the link click doesn't work.
